spring.application.name=KG25
#dbms
# 1. db 설정
# DataSource 설정 : 커넥션풀
spring.datasource.url=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=
spring.datasource.password=
# JPA 설정
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
# 한글 엔코딩 설정
server.servlet.encoding.force=true
# 2. 파일 업로드 설정
spring.servlet.multipart.enabled=true
# 파일 하나당 최대크기
spring.servlet.multipart.max-file-size=5MB
# 파일 최대 가능 업로드 크기
spring.servlet.multipart.max-request-size=10MB
# 업로드 경로
project.upload.path=